### ISSUE TITLE
Installation on Ubuntu 18.10

### ISSUE THREAD

**Issue by sojusnik** [maoschanz/dynamic-wallpaper-editor#11]
What's the proper way to install this on Ubuntu 18.10? Can't find it in the readme.

**Comment by maoschanz** [comment]
you can use the flatpak package from the last release https://github.com/maoschanz/dynamic-wallpaper-editor/releases

**Comment by sojusnik** [comment]
Great, thanks!

**Comment by sojusnik** [comment]
I see only a .flatpak file in the Releases. Normally a .flatpakref file is need. Or is there another way to install it via flatpak?

**Comment by sojusnik** [comment]
Thanks, that worked!

Would love to see this package on Flathub!
