### ISSUE TITLE
Assigning folders

### ISSUE THREAD

**Issue by sojusnik** [maoschanz/dynamic-wallpaper-editor#12]
Do you know if it's possible to assign folders instead of pictures in those .xml files?

The idea behind is to create, let's say 4 folders for each day segment (morning, day, evening, night), fill them with appropriate wallpapers, so that they would be picked randomly from those folders at an interval your app is setting. In this way you could roughly reproduce the different times of the day on your desktop.

**Comment by maoschanz** [comment]
XML wallpapers is a default thing from GNOME, this app is mostly a script producing a valid XML file. Once closed, the app has no power over the wallpaper, everything is managed by default but hidden GNOME features. The app doesn't run in the background, so it can't change things randomly at a specific interval.

If you want to reproduce the different times of the day, set the start time to 7am and add wallpapers with the right amount of time (the total should be 86400 seconds or something like that)

**Comment by sojusnik** [comment]
Thanks for the clarification!
