### ISSUE TITLE
Documentation of tooling and how to contribute

### ISSUE THREAD

**Issue by rkmax** [maoschanz/dynamic-wallpaper-editor#13]
Hi, I'm interest on the project. would be great if could add some basic steps on the readme about 

- how to compile
- how to generate a "distribution"
- small steps to contribute

In that way will be easier for people to contribute to the project :smiley:

**Comment by maoschanz** [comment]
>how to compile

To be honest i don't know it myself, i let GNOME Builder do its thing

>how to generate a "distribution"

What do you mean ?

>small steps to contribute

I will do it this week-end

**Comment by rkmax** [comment]
- a brief mention of the use of gnome builder on the readme is enough to know what tool use
- How to generate a distribution, well this parte is related to the first question, an example: how to generate a .flatpak file or something like a tarball to distribute
- and about how to contribute if you also may have some list of goals or something to align the effort also will be nice

**Comment by maoschanz** [comment]
I only know how to do a flatpak file (there is a button for it in GNOME Builder), i don't think this app is useful enough to worth the time doing packages for each distro

**Comment by maoschanz** [comment]
I wrote some commands but i don't know the exact list of dependencies so you should use GNOME Builder with the flatpak runtime anyway

**Comment by rkmax** [comment]
I was able to run it yesterday by just opening from meson.build file on Gnome Builder, it's incredible that I'm using linux for 10 years and never tested Gnome Builder :sweat_smile: 

I'll start with an easy thing, translate to spanish and will report a couple of thing I saw. thanks for the headlights

**Comment by maoschanz** [comment]
Be careful, I just updated a ton of things, so your fork might not be mergeable anymore
