### ISSUE TITLE
Mysterious file corruptions

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/dynamic-wallpaper-editor#16]
Saving a file *sometimes* produces a corrupted XML file (sometimes only the 1st characters, somtimes only the last, sometimes everything).

Saving it *again* then often fix the issue.

Why ? Is it a problem with my app ? With Gio.File ? With flatpak portals ?

**Comment by F3l1XQu1ll** [comment]
Hi, I've looked it up and I think it's the `self.gio_file.replace_contents_async(...)` call in the action_save method (at line 719 in window.py). I tried `self.gio_file.replace_contents(contents, None, False, \
                                 Gio.FileCreateFlags.NONE, None)` and everything worked.

**Comment by maoschanz** [comment]
be careful, these corruptions are not systematic, in the current version you need a bit of luck to reproduce them, i'll merge it to test but it will need some testing

**Comment by F3l1XQu1ll** [comment]
After all the changes happened and all the tests associated with them, I think this is fixed now …

**Comment by maoschanz** [comment]
yes, i think too, i'll release a new version tomorrow
