### ISSUE TITLE
Start time is off by 1 hour

### ISSUE THREAD

**Issue by jasonames42** [maoschanz/dynamic-wallpaper-editor#35]
I don't know if anyone else is getting this problem, but I set my "start time" to 7:00:00, as my night time picture spans from before to after midnight. I noticed it is starting at 6 instead of 7. I changed the start time to 8 in the app, and now it starts at 7. I'm running Manjaro Gnome, time zone is EST, hardware clock is set to local (dual boot situation)

**Comment by maoschanz** [comment]
isn't it a summer/winter hour issue?

**Comment by jasonames42** [comment]
Since it is standard time in the winter, I would only expect the hour
off behavior in the summer (daylight savings time). I played with the
xml itself, and it seems the issue is with gnome, not the app. Sorry
for the report, the app is building the xml as it should. I'll have to
experiment more to see where the hour difference is coming from.On Mon,
2019-12-02 at 12:20 -0800, Romain F. T. wrote:

**Comment by maoschanz** [comment]
ok, sorry i couldn't help
