### ISSUE TITLE
Natural sort when opening a folder

### ISSUE THREAD

**Issue by e-minguez** [maoschanz/dynamic-wallpaper-editor#40]
I'm using the flatpak in Fedora 31 and I had a folder with 24 files as:

```
0.jpg
1.jpg
...
23.jpg
24.jpg
```

When I open the folder, they are ordered as:

```
0.jpg
1.jpg
10.jpg
11.jpg
...
2.jpg
20.jpg
...
```

Which is a PITA because I need to drag a drop almost all of them.

Thanks!

**Comment by maoschanz** [comment]
Ordering could be a feature even when images are added individually or when opening an existing XML file
