### ISSUE TITLE
dconf access not working after upgrading to runtime 3.36 

### ISSUE THREAD

**Issue by ShashikanthChill** [maoschanz/dynamic-wallpaper-editor#41]
I believe after update, the application is not able to set wallpapers. I've added couple of new images to a pre-configured xml file and clicked on 'Set Wallpaper' option. But nothing happens.

I do get this message in cli when I launch the app: 

`Gtk-Message: 13:10:58.845: Failed to load module "pk-gtk-module"`

**Comment by maoschanz** [comment]
is it installed [as a flatpak package](https://github.com/flathub/com.github.maoschanz.DynamicWallpaperEditor/pull/3)?

**Comment by ShashikanthChill** [comment]
> is it installed [as a flatpak package](https://github.com/flathub/com.github.maoschanz.DynamicWallpaperEditor/pull/3)?

Yes it is. I already ran `flatpak update`

**Comment by ShashikanthChill** [comment]
Okay, so the rpm package is working fine. I guess flatpak needs in the flathub. I'm closing the issue.

**Comment by maoschanz** [comment]
i let it open until i rollback the changes done on flathub
