### ISSUE TITLE
New app icon?

### ISSUE THREAD

**Issue by bertob** [maoschanz/dynamic-wallpaper-editor#42]
The current icon is a bit flat and simplistic, would you be interested in one that more closely follows the HIG? If so, I'd be happy to help with this.

**Comment by maoschanz** [comment]
Yes but i like the current design, i think it carries well the general idea of what the app is/does. If you do something more professional than my poor attempt at Inkscape, i'd like the icon to keep the same concepts

**Comment by bertob** [comment]
Makes sense, I agree that the current metaphor is good. Here's an attempt at doing the same thing in a more HIG-compliant way:

![image](https://user-images.githubusercontent.com/1908896/81476962-27ec7d80-9215-11ea-8306-cf806bbb06bd.png)

**Comment by maoschanz** [comment]
could you try other colors for the gradient?

**Comment by bertob** [comment]
Do you have anything specific in mind?

Here's a variation with more colors:

![image](https://user-images.githubusercontent.com/1908896/81541549-8e87ad80-9373-11ea-94c8-88cd4ac7d8a0.png)

**Comment by maoschanz** [comment]
this one is nice, it feels warmer

**Comment by bertob** [comment]
Ok, do you want me to make an MR?

**Comment by maoschanz** [comment]
i think you've forgotten to finish the symbolic one 😅 then yes, you can also replace my name by yours in the "artists" field of the "about" dialog (`main.py`)
