### ISSUE TITLE
Translate help files?

### ISSUE THREAD

**Issue by rffontenelle** [maoschanz/dynamic-wallpaper-editor#48]
Currently it consists of 47 strings to translate, and it would require the following changes:
- `./update-translations.sh` — also generate POT and update PO of help files
- `help/LINGUAS` — hold one language code per line; meson.build will read to build and install translated help
- `help/dynamic-wallpaper-editor.pot` — create using adapted update-translations.sh
- `CONTRIBUTING.md` — include instructions on translating help files

Are you interested in a pull request that enables translation of help files?

**Comment by maoschanz** [comment]
Will these translations consist in new strings to the .po files, separate .po files, or entirely independant help pages for each language?

**Comment by rffontenelle** [comment]
Separated from UI .po files, stored in `help/<lang>/<lang>.po` (e.g. help/fr/fr.po). When running `ninja install`, this will also build the translated documentation and install it in `share/help/<lang>/`, similar to the original `share/help/C`

**Comment by maoschanz** [comment]
ok then (but don't push any .pot file for now, the current help manual is outdated)

**Comment by rffontenelle** [comment]
Roger that
