### ISSUE TITLE
Can't apply wallpaper on Budgie

### ISSUE THREAD

**Issue by Khrona98** [maoschanz/dynamic-wallpaper-editor#54]
Hello there!

I just found this program on Flathub as I was looking for a way to set different wallpapers depending on the time of the day, but unfortunately it looks like this doesn't support Budgie as it throws this error when trying to apply:

![Screenshot from 2020-06-29 22:18:34](https://user-images.githubusercontent.com/9277125/86071788-833d2e00-ba56-11ea-9c79-94c2a0255f57.png)

Would it be possible for you to support for this DE?

It's totally fine if you don't, but I decided to post this issue just in case.

**Comment by maoschanz** [comment]
iirc, last time i tested, it really didn't work on Budgie, hence the message

i'll test again if i have time

meanwhile if you know where the Budgie background is in dconf, you can set your XML file as wallpaper from the dconf-editor app

**Comment by F3l1XQu1ll** [comment]
Since Budgie has its own app to change the wallpaper, I would think it does not support XML files …
[](https://github.com/UbuntuBudgie/budgie-extras/tree/master/budgie-wallstreet)
If you don't want dynamic times, it has all the functionality you need.

**Comment by maoschanz** [comment]
Cinnamon also has its own thing too, you can set folders as wallpaper to do a simple slideshow for example. But it supports XML files anyway.

Budgie probably has an other problem somewhere

**Comment by fossfreedom** [comment]
Budgie desktop does not support gnome shell XML files.

Wallpaper handling is limited to standard png and jpg files via the normal gnome dconf key.

**Comment by maoschanz** [comment]
i'll close the issue when i'll have added explicitly this information to the readme and the help pages
