### ISSUE TITLE
[daylight] special labels when a duration is 0

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/dynamic-wallpaper-editor#58]
example: ![Capture d’écran de 2020-07-21 23-53-36](https://user-images.githubusercontent.com/19996113/88111197-cc902180-cbad-11ea-9239-206ec9e92979.png)

btw the automatic fix should maybe set transitions??

**Comment by F3l1XQu1ll** [comment]
Yes there should be some label, as it currently looks kinda broken.
And automatic transitions would be nice to have, but I'm not sure how this should be done.
This should be a separate issue.
