### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bertob** [maoschanz/dynamic-wallpaper-editor#63]
Would be nice to get a new release soonish, even if it just includes the new icon. It'd look so much nicer on Flathub et al ;)

**Comment by maoschanz** [comment]
>even if it just includes the new icon

sadly the unfinished features can't be released with it

let's see next week

**Comment by GustavoPeredo** [comment]
Maybe a minor dot release (2.5.1)? The pt_BR translation has some annoying translation issues (and the new icon looks super pretty!).

Do you have a list of things that still need to be done? I can create a pull request doing some of them

**Comment by maoschanz** [comment]
sadly there are no branches on this repo, i can't do minor releases, i have to finish what i started before i can release anything

**Comment by GustavoPeredo** [comment]
If you want, you can assign me to finish one of the issues.
