### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by Mek101** [maoschanz/dynamic-wallpaper-editor#69]
Where does `type = "overlay"` come from? I tried to search the net for different types of translations, but I wasn't able to find absolutely anything documenting it

https://github.com/maoschanz/dynamic-wallpaper-editor/blob/dc6fc40b83acb3823c85846f213c6419514fc908/src/picture_widget.py#L203

**Comment by maoschanz** [comment]
it comes from `/usr/share/backgrounds/gnome/adwaita-timed.xml` which is the model i used. I've no idea if there are other possible values, or if it does anything at all, but i would be happy to know (it could be an option)
