### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [maoschanz/dynamic-wallpaper-editor#81]
The current appdata summary `Create or edit XML dynamic wallpapers ("background slideshows") for the GNOME desktop` is not good for a number of reasons:
- Too long (should be <=35 characters)
- Mentions the target environment (that can go in the description, but not the summary)
- Too much technical detail

I'd go with something much shorter and simpler, e.g. `Create wallpaper slideshows`.

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by maoschanz** [comment]
>Mentions the target environment (that can go in the description, but not the summary)

GNOME is more than a target environment, that XML format for wallpapers is defined by (and read by) `libgnome-desktop`, it wouldn't work on KDE or Budgie for example

ok for the other points tho

**Comment by bertob** [comment]
FYI `Create or edit dynamic wallpapers for GNOME` is still a bit too long. Maybe `Make dynamic wallpapers for GNOME`?

**Comment by maoschanz** [comment]
i did that because it was already this sentence in the "about" dialog, so it's already translated 😅 i'll drop the "or edit" later i think, but 38 characters is close enough for now
