### ISSUE TITLE
Question about "Daylight"

### ISSUE THREAD

**Issue by Etamuk** [maoschanz/dynamic-wallpaper-editor#83]
Hello,

I am working on German translation of this app.
But I have some trouble with the meaning of "Daylight" (for example: "Fit the daylight").

Does it mean the time from sunrise to sun sundown? Or does it mean all the time from 0:00 to 0:00?

**Comment by maoschanz** [comment]
such a wallpaper has a duration of 24 hours precisely, starting at the hour the user sets in the "start time" popover (maybe 6:00 or 7:00 by default? maybe 0:00 as you say, i don't remember), the point is that they would use darker images during the night and lighter ones during the day, so the luminosity of the wallpaper fits the luminosity of the sky

i'm not a native english speaker so there might be better words, if you have an idea you can suggest

**Comment by Etamuk** [comment]
Thank you for explaining. 
I think I found a good translation for that in German language.
"Daylight" in German means exactly the whole time when the sun comes up to the time the sun goes down. So the course of the day might be a better description (this includes the evening, morning and also the time, the sun comes up but you can´t the see sun light directly....) Hard to explain. :-) 
But it´s done :-D
