### ISSUE TITLE
Support symbolic links

### ISSUE THREAD

**Issue by schreiberste** [maoschanz/dynamic-wallpaper-editor#85]
I have a wallpapers folder that contains some links to images stored in other locations.
Unfortunately, the Dynamic Wallpaper Editor does not work with these links, even though it is no problem to have the links in the wallpaper .xml

Support for links would be great, thanks!

Steffen

Dynamic Wallpaper Editor 2.7
Debian 11, Flatpak 1.10.2

**Comment by maoschanz** [comment]
i'm not sure whether it's a problem from the app or from flatpak but if it's possible i'll try

**Comment by schreiberste** [comment]
Thanks for having a look!
Indeed, it worked after giving the flatpak app access to all files with
`flatpak override com.github.maoschanz.DynamicWallpaperEditor --filesystem=host`

**Comment by maoschanz** [comment]
because the images were outside /home/user?

**Comment by schreiberste** [comment]
Yes, exactly.
